### ISSUE TITLE
Linux 运行库导入问题

### ISSUE THREAD

**Issue by BL-GS** [zaglc/EI6705-037-M01-DistCam#6]
OS：Fedora 41 - Linux 6.11.6
Python: 3.11
在分支 `develop` 执行 `python3 run.py` 时报错

![80e11803fea5c1c58e382dc94f2d590c_720](https://github.com/user-attachments/assets/cfe079b0-ec27-49dd-986d-9de94d8ad4ea)

**Comment by zaglc** [comment]
[https://github.com/zaglc/EI6705-037-M01-DistCam/pull/5](url) 已修复这一问题
